version: '3.8'
services:
  kiosko-app:
    container_name: Kiosko-App
    image: registry.gobdigital.com/nomina/kiosko_app
    ports:
      - 3000:3000
    environment:
      ENV: local
      PORT: 3000
      SECRET: secret
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: 192.168.1.1
      DB_PORT: 1433
      DB_NAME: NF_XXX

      IMAGE_DB_HOST: 192.168.1.1
      IMAGE_DB_PORT: 1433
      IMAGE_DB_DATABASE: RNF_XXX
      IMAGE_DB_USERNAME: user
      IMAGE_DB_PASSWORD: password
    restart: always