export * from './codigos.entity'
export * from './empleado.entity'
export * from './estado.entity'
export * from './estado_civil.entity'
export * from './nacionalidad.entity'
export * from './razon_social.entity'
export * from './supervisor.entity'
