export * from './estatus.entity'
export * from './incapacidades.entity'
export * from './incidencias.entity'
export * from './justificantes.entity'
export * from './bitacora.entity'
export * from './evidencia.entity'
export * from './tenant.entity'
